### ISSUE TITLE
ROS javascript library does not always accept custom message types

### ISSUE THREAD

**Issue by vashmata** [space-concordia-robotics/robotics-prototype#128]
Note that this issue is low priority. While rosifying the GUI, certain message types were defined. For example, a lightweight message type for navigation data was created. However, roslibjs would not recognize the message type. Some internet searches revealed that this issue has been discovered by others as well.

In the meantime, default message types such as Point are being used instead. They pose no problems, it's just that having custom messages would make it more clear what certain messages are for.

**Comment by PeterGhimself** [comment]
@vashmata still relevant? :eyes:

**Comment by vashmata** [comment]
Still relevant.

**Comment by PeterGhimself** [comment]
Since this issue seems to be known to the general public, is this issue a work around? Would this mean that a proper fix would mean that the roslibjs devs fix it on their end? Do we have the most up to date version of roslibjs/is the problem already resolved since this issue was opened?

Might be worth while to check [this](https://github.com/RobotWebTools/roslibjs) out :eyes:

**Comment by AFknUsername** [comment]
I know this is old, but I believe my current PR #366 should solve any issues with ROS message types.
Maybe revive this and make sure that there are no more issues?
