### ISSUE TITLE
Improve confusing naming scheme of camera servo pins

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#174]
- [ ] call them pan/tilt instead of side/base

See : https://github.com/space-concordia-robotics/robotics-prototype/commit/46a28fa0168fcf09380338e88b9e3291eba176f2

**Comment by vashmata** [comment]
Related note, make sure that the pin names also correspond to the labels in the electrical schematics. And make sure the names are changed in the mcu code as well as in the js (and html?).

While we're at it, maybe this relates to #173 but we should also make sure the wheel motor naming scheme is standardized across the board so that everyone agrees on it. The names in the microcontroller code aren't the same as those in the electrical schematics for example. Not sure about the js (and html?).
