### ISSUE TITLE
Users shall be able to view the camera feed

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#22]
Use cases:
- 4.1.11 Enable camera feed
This is a button to allow the user to enable video stream. When enabled this also includes the action of allowing the camera to send the feed to the GUI application.
- 4.1.12 Disable camera stream
This is a button to allow the user to disable video stream. This is useful since it allows the number of requests and data received to be reduced, which could improve performance when needed.
- 4.1.15 Update camera FPS
The camera feed has the potential of causing performance issues due to the number of data being fed to the GUI application. To reduce this load decreasing frames per second will be necessary, This could make the image rendered a bit blurred but this will be OK.

**Comment by bnduwi** [comment]
@ZaynMuhammad I think you are working on this issue. When your ready you can use Zenhub (chrome extension) to move it to in progress.

**Comment by bnduwi** [comment]
Tested out the code on branch https://github.com/space-concordia-robotics/robotics-prototype/issues/13.
OpenCV setup on windows was went ok.
Ran the StreamCatcher.py program and saw the camera feed from my laptop.
Pressing q did close the feed.
Good job Zayn

**Comment by bnduwi** [comment]
Since we'll eventually switch to using Flask I started looking at how it can be done. Found this link: https://blog.miguelgrinberg.com/post/flask-video-streaming-revisited
The code for it on this github: https://github.com/miguelgrinberg/flask-video-streaming

I tested it out and it was able to provide a camera feed in the browser.
![image](https://user-images.githubusercontent.com/32171245/42414282-e7010bb4-81ff-11e8-9c71-0f3c71b0d8ee.png)

![image](https://user-images.githubusercontent.com/32171245/42414294-2db0af7e-8200-11e8-95c6-8b949bb96183.png)

Above is view of running it using cmd since an environment variable has to be set to use opencv
i.e: set CAMERA=opencv (in Windows) 

Next image shows viewing the feed in browser (note have to use 125.0.0.1 instead of feedback loop as mentioned in cmd image)

**Comment by gabrielkarras** [comment]
For issue #22 and #23, you'll need to install OpenCV on your machine as we'll be using it to develop/work with the camera. Follow this installation tutorial (link below). We'll proceed to import Zayn's code for GTK to Flask (my task).
 
_Installation tutorial_: https://medium.com/@debugvn/installing-opencv-3-3-0-on-ubuntu-16-04-lts-7db376f93961.

**Comment by PeterGhimself** [comment]
Work started on branch [view-camera-feed-22](/space-concordia-robotics/robotics-prototype/tree/view-camera-feed-22)
