### ISSUE TITLE
Simple action template demo

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#256]
## Problem
To start with our first autonomy module we need a simple straight line goal planner with the ultimate purpose of driving the rover from it's current GPS coordinate to a destination coordinate provided by the client. We would ultimately like to use a ROS action to perform this task. A demo should be created for new members to easily reference for creating future actions.

*Note each step should be well documented*

## Sub tasks
- [x] Research ROS action server/client
- [x] Setup a boilerplate ROS action client
- [x] Setup a boilerplate ROS action server
- [x] Add the action template demo to the robot/demos folder under "RosAction"

**Comment by vashmata** [comment]
This past week we succeeded in running the actionlib beginner tutorial. Continuing forwards the autonomy team will continue learning about actions and attempt to create one themselves.

**Comment by KoaTheKoala** [comment]
I added two ROS Action/Server demos for reference. The first one is just based off of the ROS action tutorial linked here: http://wiki.ros.org/actionlib_tutorials/Tutorials

The first demo is for calculating a set of numbers in the Fibonacci sequence.
The second demo is for 'washing dishes' by controlling a for loop control variable.

See the readme in robotics-prototype/robot/demos/RosAction/ for more information. The long version of the readme will contain condensed steps to building an action from scratch. It's partially done. I will finish it soon. Otherwise, we are ready to go to start building custom actions -insert sunglasses emoji-

**Comment by vashmata** [comment]
@PeterGhimself @MartensCedric I find it a bit weird that we would keep ROS demos in a place where we can't actually run them. I would propose we make a package called Demos within rospackages where we hold them so that people can run themm right away

**Comment by vashmata** [comment]
I have a few other demo ROS scripts that I need to relocate as well
