### ISSUE TITLE
Proper import statement unit test

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#270]
In [this](https://github.com/space-concordia-robotics/robotics-prototype/commit/2d7c76e7f89b7f6a14a655c3fd4fe24c92465979) commit we removed the motor_test unit test since we removed a class `motor.py` which was in `basestation` folder since we though it wasn't being used.

While it may have no functional use for the project, it is a good proof that our repo built correctly in that `setup.py develop` worked properly and we can import our own custom modules with the `robot.basestation.etc` format.

A new test should be made only to test that the import statements on our custom modules are working as they should after building the projects,

- [x] Add unit test to verify `python setup.py develop` suceeded during the build

**Comment by MartensCedric** [comment]
Since the purpose of this issue is not _actually_ to add `motor.py` back but to actually see if the imports are correct. I suggest that instead of adding a seemingly useless class back as a unit test we create a new unit test that validates that the imports are done correctly. This is also for the future developers on the project, which will immediately see its importance instead of doubting its utility.
@PeterGhimself

**Comment by PeterGhimself** [comment]
Fair enough @MartensCedric
