### ISSUE TITLE
Replace all #IFNDEF directives with #pragma once

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#277]
This issue suggests that we should instead of using `#IFNDEF... #DEFINE` directives in our cpp code should have the header files themselves define this behavior with `#pragma once`.

This should have the same effect on the code/compilation of it but reduce SLOC.

**Comment by vashmata** [comment]
According to my googling, the pragma directive only applies to compiler settings for machine/OS specific configurations. Doesn't this mean that it wouldn't be applicable in most of the situations where the ifndef directives are used, since it's stuff I made up in most cases? Unless I misunderstood the context. See more here: https://docs.microsoft.com/en-us/cpp/preprocessor/pragma-directives-and-the-pragma-keyword?view=vs-2019

As an aside, during my googling I noticed that there's a C99 version `_Pragma` which may allow for more flexibility in define directives. See more here: https://gcc.gnu.org/onlinedocs/cpp/Pragmas.html
