### ISSUE TITLE
Create Canvas with Rover Heading

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#288]
A canvas to replace the current placeholder should be put in place showing the rover heading. The direction the rover points at can be displayed by a circle with an arrow. The rover should always be centered at the middle of the canvas.

**Comment by vashmata** [comment]
I always get the terms mixed up so here's a link to the definitions of heading and bearing: https://aviation.stackexchange.com/questions/8000/what-are-the-differences-between-bearing-vs-course-vs-direction-vs-heading-vs-tr

**Comment by MartensCedric** [comment]
your right @vashmata .

F

well im gonna update it to heading

**Comment by vashmata** [comment]
I had some thoughts pop into my head that I'm keeping here for future reference:
1) during autonomy, we will only be setting one GPS goal per leg
2) during extreme delivery, there should be a way to select the desired goal out of all the goals, because this one is what tells the rover which direction to turn to. Ideally it will also be obvious which goal is the target. Speaking of which, the relative bearing between the rover and its goal needs to be displayed somewhere, would this go on the canvas or on the side somewhere?

**Comment by MartensCedric** [comment]
![image](https://user-images.githubusercontent.com/18620025/74089226-215f3600-4a6d-11ea-815b-c5951a0496ab.png)
Perhaps we should place the GPS canvas besides this nav screen that @steamypotato did. What do you think @mattsklivas ? @PeterGhimself @vashmata @KoaTheKoala

**Comment by vashmata** [comment]
Makes sense, as long as this page is near the camera feeds and the wheel controls so that everyone knows what's going on
