### ISSUE TITLE
Inform operator of optimal antenna direction

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#291]
The operator should know what orientation the antenna should be in. There is already code in a node done by @Waleed-HM 

- [ ] Indicator of what direction the antenna should be pointing in the gui

**Comment by vashmata** [comment]
It's actually the opposite. Rather than the GUI displaying the direction that the antenna IS facing, the GUI must tell the operators which direction the antenna SHOULD face and it's the operators who adjust the antenna to accommodate that.

**Comment by vashmata** [comment]
The ability to display the antenna on the canvas also implies that you need a GUI element that you can use to enter in the coordinates of the antenna. AntennaNode.py expects the user to send it latitude, longitude and initial antenna direction (I believe it's the angle with respect to North but this is where @Waleed-HM can provide information)

**Comment by MartensCedric** [comment]
@vashmata so that has nothing to do with this GPS canvas Epic then?

**Comment by MartensCedric** [comment]
I repurposed this issue

**Comment by Waleed-HM** [comment]
Add me as a participant to this issue.
It's been a while since I worked on this but yeah, that's the gist of it.
The code I wrote before needs the initial antenna direction with respect to north, and using the feedback from the rover GPS chip, it gives you the number you should manually set on the rotator device. Sadly I don't think there is a way to automate this as the rotator device is AC and doesn't have any sort of interface we can use.
Let us discuss this more on Saturday.

**Comment by MartensCedric** [comment]
@steamypotato was this done in your #287 ?

**Comment by vashmata** [comment]
In #297 I revive the old navigation pane and the antenna director calculations still do stuff.

**Comment by MartensCedric** [comment]
Also the new code of @steamypotato once merge will improve the visual
layout of this displayed information
