### ISSUE TITLE
Disable arm motors

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#33]
- [ ] Activating/Deactivating
- - [ ] Implement MCU feature
- - [ ] Implement GUI link
- [ ] Disabling (power)
- - [ ] Hardware ready (PDS updated)
- - [ ] Per motor disabling
- - [ ] All at once
- - [ ] Update PDS page on GUI to include features

**Comment by vashmata** [comment]
Issue is not quite relevant anymore since there is no way to enable or cut power to the arm motors. That said we are able to turn the arm listener on and off through the GUI. We could implement an activate/deactivate functionality either in the GUI or the microcontroller but the current implementation seems very safe even without this safety feature.

**Comment by PeterGhimself** [comment]
@vashmata I agree we should add the activate/deactivate functionality like all the other MCUs currently have implemented, and once we have an updated PDS situation where it can control the Arm we start work on that
