### ISSUE TITLE
Refactor the PDS Node

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#374]
The PDS node has extremely odd for loops and could definitely be improved through some refactoring. This task is to rewrite the structure of the PDS node so that it has high quality code.

**Comment by vashmata** [comment]
I don't remember if it's the case with the PDS node but a bunch of the MCU nodes are a bit weird simply due to me trying to figure out how to get them to behave as publishers, subscribers, services and whatnot all at the same time. So if you happen to start working on very big structural changes try to be thorough about testing everything.

also FYI #207 is something you might be interested in tackling at some point as it's related to refactoring these nodes :)

**Comment by AFknUsername** [comment]
Thanks for the heads up @vashmata 
Looks like #207 is already being worked on, but I'll definitely check if there is anything else to refactor.
Also, since we got the custom message types figured out, it's a really good opportunity to rework the code

**Comment by vashmata** [comment]
yeah my bad I just noticed this https://github.com/space-concordia-robotics/robotics-prototype/pull/282
I've just been going through all my emails that i accumulated in the past 2 weeks haha
