### ISSUE TITLE
Twisted Security Alerts

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#387]
I added this library to fix the rosbridge venv issue, but it ended up being useless. Now we have security alerts for this library.

I'm 95% sure this library can be removed safely. If this is not the case then we should just upgrade it so we don't get these security alerts on our repo and everytime we push.

**Comment by PeterGhimself** [comment]
I looked into this a while ago, I tried updating it and this resulted in some dependency clashes making it not possible to run the GUI.

**Comment by AFknUsername** [comment]
@MartensCedric I tried to uninstall Twisted using pip and it broke ROS. It uses it for some things like logging. 
@PeterGhimself I upgraded using `pip install -U Twisted` and it worked fine. GUI seems to be fine as well.

Thoughts?

**Comment by MartensCedric** [comment]
The library should not even be used. Idk why it broke ROS for you but this is something I added in September. 

https://github.com/space-concordia-robotics/robotics-prototype/pull/154

And this PR actually did not fix the issue so it should be safe to just undo these changes.

**Comment by AFknUsername** [comment]
This is what happens when I install latest Twisted using pip3: 
<img width="972" alt="Screen Shot 2020-06-13 at 12 09 36 PM" src="https://user-images.githubusercontent.com/34408555/84573500-d6349700-ad6e-11ea-951c-dc5dc6e11044.png">

Side note: we prob can remove the attrs requirement from requirements.txt since Twisted installs it.

**Comment by PeterGhimself** [comment]
closing via #398
