### ISSUE TITLE
GUI Styling

### ISSUE THREAD

**Issue by tatumalenko** [space-concordia-robotics/robotics-prototype#39]
# GUI Styling
We should take a few moments to talk about styling of the GUI. It's obviously not pressing, but depending on our opinions, implementation could be as easy as two lines +- of code. 

Styling currently employed is very colourful. I propose going for a nice, clean, ui look that is akin to Mac users. This is an example of how the ui would look without much doing honestly to the default GTK styling built-in:
![Minimalist theme](https://user-images.githubusercontent.com/6502401/40339804-0da897f8-5d4a-11e8-89cf-2bfd308c6cd3.png)

Obviously it's pretty darn vanilla looking, but nonetheless, with a few accentuated styling choices like adding more of that exact same blue to different actions (mouseover or button pressed, etc) could spice it up.

There's also another option, maybe a unicolour theme that relies on one principle colour and applying it in various tones. This idea is exemplified in the following image:
![Unicolor tones theme](https://user-images.githubusercontent.com/6502401/40339907-83c6727a-5d4a-11e8-8915-e53492ff3d3c.png)

What does everyone think? Let the discussions begin.

**Comment by bnduwi** [comment]
I think this is a good idea. Definitely the UI needs some revamping. It current looks as is because of experimentation to see how things work in GTK.

I like the single color with different tones idea and also the hover over color change would be great. Another thing but really not important is layout to maybe make look more like a dashboard with the controlls in the middle and a lot bigger for easier view. Just a thought ...

**Comment by tatumalenko** [comment]
What do you guys think of [this](https://github.com/dpgaspar/Flask-AppBuilder) Python Flask app look?

**Comment by PeterGhimself** [comment]
I think we should have our own predefined themes (set up default one).
Would be cool to also let the user create their own custom themes as well.

**Comment by vashmata** [comment]
Closing via #42, #55
